name: 'Shared Values'
author: 'jemmons'
description: 'Common values shared across actions.'
outputs:
  ccVersion:
    description: Version of the Code Climate coverage tool to download/cache.
  ccDirectory:
    description: Directory where Code Climate coverage tool is downloaded (mostly for caching).
  ccPath:
    description: The relative file path of the Code Climate coverage binary. 
  resultPath:
    description: File path of the Xcode results file.
  buildCachePath:
    description: File path of Xcode build artifacts (for caching).
  swiftVersion:
    description: Version of the command line Swift tool.
  project:
    description: Name of the project.

runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'dollar-sign'
  color: 'orange'
